#!/bin/bash
#
# vim-anywhere - use Vim whenever, wherever
#
# Author: Chris Knadler
# Contact: takeshi91k@gmail.com
# Homepage: https://www.github.com/cknadler/vim-anywhere

dir=/private/tmp/vim-anywhere
file=$dir/doc-$(date +"%y%m%d%H%M%S")
mkdir -p $dir

# start MacVim but don't fork (this will block until you finish editing)
mvim --nofork $file
# copy the result and refocus the previous application
cat $file | pbcopy
osascript $HOME/.vim-anywhere/tab-back.scpt
