#!/bin/bash
#
# vim-anywhere - use Vim whenever, wherever
# Author: Chris Knadler
# Homepage: https://www.github.com/cknadler/vim-anywhere
#
# Uninstalls vim-anywhere

set -e

###
# defs
###

check_installed() { hash $1 &> /dev/null; }

aw_path=$HOME/.vim-anywhere
doc_path=/tmp/vim-anywhere

###
# uninstall
###

rm -rf $aw_path $doc_path

# Linux uninstall
if [[ $OSTYPE == "linux-gnu" ]]; then
  if check_installed gconftool; then
    kbd_path=/desktop/gnome/keybindings/vim-anywhere
    gconftool --unset $kbd_path/name
    gconftool --unset $kbd_path/binding
    gconftool --unset $kbd_path/action

  else # gsettings must be installed
    custom_kbd=org.gnome.settings-daemon.plugins.media-keys.custom-keybinding
    kbd_path=/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/vim-anywhere/
    gsettings reset-recursively $custom_kbd:$kbd_path
  fi

# OSX uninstall
elif [[ $OSTYPE == "darwin"* ]]; then
  rm -rf $HOME/Library/Services/VimAnywhere.workflow
fi

echo "vim-anywhere has been successfully uninstalled!"
