#!/bin/bash
#
# vim-anywhere - use Vim whenever, wherever
# Author: Chris Knadler
# Homepage: https://www.github.com/cknadler/vim-anywhere
#
# Uninstalls vim-anywhere.

# If we are on Linux
if [[ "$OSTYPE" == "linux-gnu" ]]; then
  rm -rf $HOME/.vim-anywhere \
         /tmp/vim-anywhere

  gconftool --unset /desktop/gnome/keybindings/vim-anywhere/name
  gconftool --unset /desktop/gnome/keybindings/vim-anywhere/binding
  gconftool --unset /desktop/gnome/keybindings/vim-anywhere/action

# If we are on a Mac
elif [[ "$OSTYPE" == "darwin"* ]]; then
  rm -rf $HOME/.vim-anywhere \
         $HOME/Library/Services/VimAnywhere.workflow \
         /private/tmp/vim-anywhere
fi

echo "vim-anywhere has been successfully uninstalled!"
