#!/bin/bash
#
# vim-anywhere - use Vim whenever, wherever
# Author: Chris Knadler
# Homepage: https://www.github.com/cknadler/vim-anywhere
#
# Updates vim-anywhere. Intended for use via curl:
#
#   $ curl -fsSL https://raw.github.com/cknadler/vim-anywhere/master/update | sh

aw_path=$HOME/.vim-anywhere

unset $(git rev-parse --local-env-vars)
pushd $aw_path
  git pull origin master
popd

cp -R $aw_path/VimAnywhere.workflow $HOME/Library/Services

echo "vim-anywhere has been successfully updated!"
