#!/bin/bash
#
# vim-anywhere - use Vim whenever, wherever
# Author: Chris Knadler
# Homepage: https://www.github.com/cknadler/vim-anywhere
#
# Updates vim-anywhere

aw_path=$HOME/.vim-anywhere

if [ ! -d $aw_path ]; then
  echo "vim-anywhere doesn't seem to be installed."
  exit 1
fi

unset $(git rev-parse --local-env-vars)
pushd $aw_path
  git pull origin master
  [ $? -ne 0 ] && exit 1
popd

# If we are on OSX
if [[ $OSTYPE == "darwin"* ]]; then
  cp -R $aw_path/VimAnywhere.workflow $HOME/Library/Services
fi

echo "vim-anywhere has been successfully updated!"
