#!/bin/bash
#
# vim-anywhere - use Vim whenever, wherever
#
# Author: Chris Knadler
# Contact: takeshi91k@gmail.com
# Homepage: https://www.github.com/cknadler/vim-anywhere

case $1 in
start )
  dir=/private/tmp/vim-anywhere
  file=$dir/doc-$(date +"%y%m%d%H%M%S")
  mkdir -p $dir
  /usr/local/bin/mvim -c "au VimLeave * !$HOME/.vim-anywhere/vim-anywhere end $file" $file
  ;;
end )
  cat $2 | pbcopy
  osascript $HOME/.vim-anywhere/tab-back.scpt
  ;;
* ) exit 1 ;;
esac
